//
//  EnglishWords.swift
//  Pantomime
//
//  Created by Mahyar on 11/19/23.
//

import Foundation

public let animals = [
    "Lion", "Tiger", "Elephant", "Leopard", "Cheetah", "Giraffe", "Zebra", "Hippo",
    "Rhinoceros", "Gorilla", "Chimpanzee", "Orangutan", "Kangaroo", "Koala", "Panda",
    "Grizzly Bear", "Polar Bear", "Wolf", "Fox", "Raccoon", "Bison", "Buffalo",
    "Elk", "Moose", "Deer", "Camel", "Gazelle", "Ibex", "Chamois", "Lemur",
    "Meerkat", "Warthog", "Hyena", "Jackal", "Ocelot", "Lynx", "Caracal", "Serval",
    "Wolverine", "Badger", "Otter", "Beaver", "Skunk", "Sloth", "Anteater", "Armadillo",
    "Porcupine", "Hedgehog", "Tapir", "Aardvark", "Kangaroo Rat", "Capibara", "Wallaby",
    "Marmot", "Groundhog", "Prairie Dog", "Dingo", "Coyote", "Tasmanian Devil", "Quokka",
    "Possum", "Rat", "Hamster", "Guinea Pig", "Chinchilla", "Ferret", "Mink", "Ermine",
    "Squirrel", "Chipmunk", "Rabbit", "Hare", "Pika", "Alpaca", "Llama", "Vicuña",
    "Donkey", "Horse", "Zebra", "Mule", "Giraffe", "Okapi", "Elephant", "Rhinoceros",
    "Hippopotamus", "Dolphin", "Whale", "Shark", "Seal", "Sea Lion", "Walrus", "Manatee",
    "Narwhal", "Beluga", "Orca", "Penguin", "Albatross", "Pelican", "Flamingo", "Swan"
]
public let foods = [
    "Apple", "Banana", "Orange", "Strawberry", "Blueberry", "Raspberry", "Mango", "Pineapple",
    "Grapes", "Watermelon", "Peach", "Cherry", "Papaya", "Kiwi", "Pear", "Plum", "Apricot",
    "Lemon", "Lime", "Grapefruit", "Coconut", "Avocado", "Broccoli", "Carrot", "Cucumber",
    "Lettuce", "Tomato", "Onion", "Garlic", "Pepper", "Cabbage", "Mushroom", "Spinach",
    "Zucchini", "Corn", "Potato", "Sweet Potato", "Butternut Squash", "Pumpkin", "Eggplant",
    "Green Beans", "Peas", "Asparagus", "Cauliflower", "Beetroot", "Radish", "Celery",
    "Rice", "Pasta", "Bread", "Pizza", "Burger", "Sandwich", "Taco", "Burrito", "Sushi",
    "Noodles", "Dumplings", "Curry", "Stir Fry", "Soup", "Salad", "Chili", "Stew",
    "Lasagna", "Risotto", "Paella", "Quiche", "Omelette", "Pancakes", "Waffles", "French Toast",
    "Cupcake", "Cake", "Pie", "Brownie", "Cookie", "Donut", "Ice Cream", "Chocolate",
    "Pudding", "Custard", "Yogurt", "Cheese", "Butter", "Milk", "Eggs", "Bacon",
    "Chicken", "Beef", "Pork", "Lamb", "Fish", "Shrimp", "Lobster", "Crab",
    "Tofu", "Tempeh", "Lentils", "Chickpeas", "Beans", "Almonds", "Walnuts", "Peanuts"
]
public let objects = [
    "Chair", "Table", "Sofa", "Lamp", "Bed", "Desk", "Bookshelf", "Cupboard",
    "Mirror", "Clock", "Television", "Computer", "Laptop", "Keyboard", "Mouse",
    "Printer", "Camera", "Smartphone", "Tablet", "Speaker", "Headphones", "Microwave",
    "Oven", "Refrigerator", "Toaster", "Blender", "Coffee Maker", "Kettle", "Dishwasher",
    "Vacuum Cleaner", "Fan", "Air Conditioner", "Heater", "Washing Machine", "Dryer",
    "Iron", "Hair Dryer", "Towel", "Toothbrush", "Toothpaste", "Soap", "Shampoo",
    "Conditioner", "Deodorant", "Razor", "Brush", "Comb", "Lotion", "Perfume",
    "Nail Clipper", "Scissors", "Hammer", "Screwdriver", "Wrench", "Drill", "Saw",
    "Pliers", "Tape Measure", "Level", "Ladder", "Bucket", "Mop", "Broom",
    "Dustpan", "Trash Can", "Recycle Bin", "Pen", "Pencil", "Marker", "Crayon",
    "Notebook", "Paper", "Book", "Envelope", "Stamp", "Scotch Tape", "Glue",
    "Stapler", "Paperclip", "Binder", "Folder", "Calendar", "Calculator", "Glasses",
    "Sunglasses", "Watch", "Backpack", "Handbag", "Suitcase", "Umbrella", "Wallet",
    "Keys", "Flashlight", "Battery", "Charger", "Candle", "Vase", "Picture Frame",
    "Painting", "Rug", "Pillow", "Blanket", "Curtain", "Plate", "Bowl", "Cup",
    "Glass", "Knife", "Fork", "Spoon", "Pot", "Pan", "Cutting Board"
]
public let countriesAndCities = [
    "Afghanistan", "Tokyo", "Albania", "New York", "Algeria", "London",
    "Andorra", "Paris", "Angola", "Moscow", "Buenos Aires", "Armenia",
    "Sydney", "Austria", "Beijing", "Azerbaijan", "Cairo", "Bangladesh",
    "Los Angeles", "Barbados", "Toronto", "Belarus", "Dubai", "Belgium",
    "Singapore", "Belize", "Rome", "Benin", "Shanghai", "Bhutan", "Berlin",
    "La Paz", "Bosnia and Herzegovina", "Amsterdam", "Botswana", "Madrid",
    "Brasília", "Brunei", "Istanbul", "Bulgaria", "Chicago", "Burkina Faso",
    "Hong Kong", "Burundi", "San Francisco", "Praia", "Cambodia",
    "Bangkok", "Cameroon", "Mumbai", "Ottawa", "Central African Republic",
    "Budapest", "Chad", "Vienna", "Santiago", "China", "Lisbon",
    "Colombia", "Copenhagen", "Comoros", "Zurich", "Congo, Democratic Republic of the",
    "Helsinki", "Congo", "Dublin", "Costa Rica", "Brussels", "Croatia",
    "Stockholm", "Cuba", "Prague"
]
public let tech = [
    "Algorithm", "API", "Application", "Array", "Artificial Intelligence", "Automation", "Bandwidth",
    "Binary", "Bit", "Blockchain", "Boolean", "Bot", "Browser", "Bug", "Cache", "Cloud Computing",
    "Compiler", "Computational", "Concurrency", "Container", "CSS", "Cybersecurity", "Data Mining",
    "Database", "Debugging", "Decryption", "Deployment", "DevOps", "Digital", "DNS", "Docker",
    "Domain", "E-commerce", "Encryption", "Endpoint", "Framework", "Frontend", "Function", "Git",
    "GitHub", "GPU", "HTML", "HTTP", "HTTPS", "IDE", "Inheritance", "IoT", "IP Address", "Java",
    "JavaScript", "JSON", "Kernel", "Key-Value Store", "Latency", "Library", "Linux", "Load Balancing",
    "Machine Learning", "Metadata", "Method", "Microservices", "Middleware", "Mobile", "Network",
    "Node", "Object-Oriented", "Open Source", "Operating System", "Packet", "PHP", "Pixel", "Platform",
    "Plugin", "Protocol", "Proxy", "Python", "Query", "Queue", "RAM", "React", "Recursion", "Redundancy",
    "Refactoring", "Repository", "REST", "Robotics", "Routing", "Ruby", "SaaS", "Scalability", "Scripting",
    "SDK", "Search Engine", "Server", "Servlet", "Session", "Socket", "Software", "SQL", "SSL", "Swift",
    "Synchronization", "Syntax", "System Software", "TCP/IP", "Thread", "UI/UX", "URL", "Virtual Machine",
    "Virtual Reality", "VPN", "Web Application", "Web Services", "WebSocket", "XML", "YAML"
]
public let Places = [
    "Great Wall of China", "Machu Picchu", "Taj Mahal", "Colosseum", "Petra",
    "Pyramids of Giza", "Stonehenge", "Acropolis of Athens", "Forbidden City", "Angkor Wat",
    "Easter Island", "Hagia Sophia", "Chichen Itza", "Alhambra", "Pompeii",
    "Roman Forum", "Palenque", "Borobudur", "Parthenon", "Tower of London",
    "Notre-Dame Cathedral", "Sphinx of Giza", "Mount Rushmore", "Versailles", "Red Fort",
    "Christ the Redeemer", "Ellis Island", "Mont Saint-Michel", "Statue of Liberty", "Louvre Museum",
    "Potala Palace", "Terracotta Army", "Mausoleum at Halicarnassus", "Hanging Gardens of Babylon",
    "Mesa Verde", "Buckingham Palace", "Berlin Wall", "Gettysburg Battlefield", "Hiroshima Peace Memorial",
    "Sistine Chapel", "Leaning Tower of Pisa", "Grand Palace", "Kremlin", "St. Peter's Basilica",
    "Tikal", "Karnak", "Luxor Temple", "Teotihuacan", "Neuschwanstein Castle",
    "Mohenjo-Daro", "Westminster Abbey", "Temple of Heaven", "Big Ben", "Independence Hall",
    "Alcatraz Island", "Edinburgh Castle", "Topkapi Palace", "Blenheim Palace", "Capitol Hill",
    "Machu Picchu", "Lincoln Memorial", "Sydney Opera House", "Forbidden City", "Himeji Castle",
    "Uluru", "Hagia Sophia", "Versailles", "Mecca", "Vatican City",
    "Old City of Jerusalem", "Istanbul", "Delphi", "Chartres Cathedral", "Auschwitz",
    "Pearl Harbor", "Borobudur", "Monticello", "Mount Vernon", "The Alamo",
    "Babylon", "Pompeii", "Ellis Island", "Chichen Itza", "Stonehenge",
    "The Colosseum", "The Louvre", "Taj Mahal", "Great Wall of China", "The Acropolis",
    "Angkor Wat", "Petra", "Machu Picchu", "Grand Canyon", "Yellowstone",
    "Mount Rushmore", "Mesa Verde", "Hiroshima Peace Memorial", "Great Pyramid of Giza", "Sphinx of Giza"
]
public let jobs = [
    "Accountant", "Actor", "Architect", "Artist", "Astronaut", "Athlete", "Attorney", "Author",
    "Baker", "Barber", "Bartender", "Biologist", "Blacksmith", "Botanist", "Builder", "Butcher",
    "Carpenter", "Chef", "Chemist", "Chiropractor", "Civil Engineer", "Cleaner", "Clerk", "Coach",
    "Computer Programmer", "Construction Worker", "Consultant", "Copywriter", "Counselor", "Dancer",
    "Data Analyst", "Dentist", "Designer", "Detective", "Dietitian", "Doctor", "Driver", "Economist",
    "Editor", "Electrician", "Engineer", "Entrepreneur", "Farmer", "Fashion Designer", "Film Director",
    "Firefighter", "Fisherman", "Florist", "Forester", "Gardener", "Geologist", "Graphic Designer",
    "Hairdresser", "Historian", "Interior Designer", "Interpreter", "Journalist", "Judge", "Lawyer",
    "Librarian", "Linguist", "Locksmith", "Magician", "Makeup Artist", "Manager", "Marketing Specialist",
    "Mason", "Mathematician", "Mechanic", "Meteorologist", "Musician", "Nurse", "Nutritionist",
    "Optician", "Painter", "Paramedic", "Pathologist", "Personal Trainer", "Pharmacist", "Photographer",
    "Physician", "Physicist", "Pilot", "Plumber", "Police Officer", "Politician", "Professor",
    "Psychologist", "Radiologist", "Real Estate Agent", "Receptionist", "Reporter", "Researcher",
    "Retail Worker", "Sailor", "Salesperson", "Scientist", "Secretary", "Security Guard", "Singer",
    "Social Worker", "Software Developer", "Surgeon", "Tailor", "Teacher", "Translator", "Travel Agent",
    "Veterinarian", "Videographer", "Waiter/Waitress", "Web Developer", "Writer", "Zoologist"
]
public let football = [
    "Lionel Messi", "Cristiano Ronaldo", "Pele", "Diego Maradona", "Neymar",
    "Zinedine Zidane", "Ronaldinho", "Johan Cruyff", "Kylian Mbappe", "Mohamed Salah",
    "Alex Ferguson", "Pep Guardiola", "Jurgen Klopp", "Jose Mourinho", "Arsene Wenger",
    "Carlo Ancelotti", "Joachim Low", "Vicente del Bosque", "Marcelo Bielsa", "Antonio Conte",
    "Camp Nou", "Wembley Stadium", "Old Trafford", "Santiago Bernabeu", "Allianz Arena",
    "San Siro", "Anfield", "Stamford Bridge", "Signal Iduna Park", "Emirates Stadium",
    "Maracana", "Estadio Azteca", "Luiz", "FIFA World Cup", "UEFA Champions League",
    "Ballon d'Or", "Goalkeeper", "Defender", "Midfielder", "Striker",
    "Offside", "Penalty", "Free Kick", "Corner Kick", "Goal",
    "Red Card", "Yellow Card", "Foul", "Substitution", "Extra Time",
    "Injury Time", "Half-Time", "VAR", "Dribbling", "Passing",
    "Tackle", "Cross", "Header", "Throw-In", "Hat-Trick",
    "Bicycle Kick", "Nutmeg", "Tiki-Taka", "Derby", "El Clasico",
    "Coppa Italia", "Bundesliga", "Premier League", "La Liga", "Serie A",
    "Ligue 1", "MLS", "Copa America", "Euro Cup", "AFC Asian Cup",
    "CAF Champions League", "Olympic Football", "Golden Boot", "Golden Glove", "Playmaker",
    "Captain", "Manager", "Referee", "Linesman", "Supporters",
    "Stadium", "Cleats", "Jersey", "Whistle", "Tactics",
    "Formation", "4-4-2", "4-3-3", "3-5-2", "Counter-Attack",
    "Possession", "Offensive", "Defensive", "Home Team", "Away Team"
]
public let sports = [
    "Soccer", "Basketball", "Baseball", "American Football", "Hockey", "Tennis", "Golf", "Rugby",
    "Cricket", "Volleyball", "Table Tennis", "Badminton", "Bowling", "Boxing", "Martial Arts",
    "Karate", "Judo", "Taekwondo", "Wrestling", "Fencing", "Archery", "Shooting", "Biathlon",
    "Skiing", "Snowboarding", "Ice Skating", "Gymnastics", "Rhythmic Gymnastics", "Trampoline",
    "Diving", "Swimming", "Water Polo", "Synchronized Swimming", "Rowing", "Canoeing", "Kayaking",
    "Sailing", "Windsurfing", "Surfing", "Paddleboarding", "Snorkeling", "Scuba Diving", "Fishing",
    "Rock Climbing", "Mountaineering", "Hiking", "Camping", "Cycling", "Mountain Biking", "BMX",
    "Skateboarding", "Roller Skating", "Inline Skating", "Scootering", "Motorsport", "Auto Racing",
    "Motorcycle Racing", "Kart Racing", "Drone Racing", "Horse Racing", "Bull Riding", "Rodeo",
    "Equestrian", "Polo", "Dressage", "Track and Field", "Marathon", "Sprint", "Hurdles", "High Jump",
    "Long Jump", "Triple Jump", "Pole Vault", "Discus Throw", "Hammer Throw", "Javelin Throw",
    "Shot Put", "Decathlon", "Heptathlon", "Pentathlon", "Triathlon", "Ironman Triathlon", "CrossFit",
    "Weightlifting", "Powerlifting", "Bodybuilding", "Aerobics", "Yoga", "Pilates", "Dance",
    "Ballet", "Cheerleading", "Parkour", "Freerunning", "Ultimate Frisbee", "Disc Golf", "Handball",
    "Lacrosse", "Field Hockey", "Softball", "Cricket", "Squash", "Racquetball", "Pickleball",
    "Badminton", "Sepak Takraw", "Kabaddi", "Sumo Wrestling"
]
public let movies = [
    "The Shawshank Redemption", "The Godfather", "The Dark Knight", "The Godfather Part II",
    "12 Angry Men", "Schindler's List", "Pulp Fiction", "The Lord of the Rings: The Return of the King",
    "The Good, the Bad and the Ugly", "Fight Club", "Forrest Gump", "Inception",
    "The Lord of the Rings: The Fellowship of the Ring", "Star Wars: Episode V - The Empire Strikes Back",
    "The Lord of the Rings: The Two Towers", "The Matrix", "Goodfellas", "One Flew Over the Cuckoo's Nest",
    "Seven Samurai", "Se7en", "City of God", "The Silence of the Lambs", "It's a Wonderful Life",
    "Life Is Beautiful", "The Usual Suspects", "Léon: The Professional", "Spirited Away",
    "Saving Private Ryan", "American History X", "Interstellar", "The Green Mile", "Parasite",
    "Psycho", "Rear Window", "Casablanca", "The Departed", "Whiplash", "Gladiator", "The Prestige",
    "The Lion King", "Memento", "Apocalypse Now", "Alien", "Blade Runner", "The Shining",
    "The Avengers", "Jurassic Park", "Titanic", "The Exorcist", "Terminator 2: Judgment Day",
    "Back to the Future", "Indiana Jones: Raiders of the Lost Ark", "Jaws", "Die Hard",
    "The Terminator", "Chinatown", "Toy Story", "Toy Story 3", "The Incredibles",
    "Finding Nemo", "Monsters, Inc.", "Up", "Inside Out", "Coco",
    "WALL-E", "The Grand Budapest Hotel", "Moonrise Kingdom", "Fargo", "No Country for Old Men",
    "The Big Lebowski", "A Clockwork Orange", "2001: A Space Odyssey", "Dr. Strangelove",
    "The Gold Rush", "Modern Times", "City Lights", "The Great Dictator", "Django Unchained",
    "Inglourious Basterds", "Kill Bill: Vol. 1", "Pulp Fiction", "Reservoir Dogs", "The Hateful Eight",
    "Gone with the Wind", "Lawrence of Arabia", "Doctor Zhivago", "Amadeus", "Braveheart",
    "The Sound of Music", "West Side Story", "Rocky", "Raging Bull", "Taxi Driver",
    "The King's Speech", "A Beautiful Mind", "La La Land", "Slumdog Millionaire", "Million Dollar Baby",
    "The Social Network", "Spotlight", "Birdman", "12 Years a Slave", "Moonlight",
    "The Shape of Water", "Manchester by the Sea", "Gravity", "Argo", "Lincoln"
]
public let proverbs = [
    "Actions speak louder than words.", "The early bird catches the worm.", "Barking up the wrong tree.",
    "A picture is worth a thousand words.", "Beauty is in the eye of the beholder.",
    "Better late than never.", "Birds of a feather flock together.", "Cleanliness is next to godliness.",
    "Don't bite the hand that feeds you.", "Don't judge a book by its cover.",
    "Easy come, easy go.", "Every cloud has a silver lining.", "Fortune favors the bold.",
    "God helps those who help themselves.", "Good things come to those who wait.",
    "Haste makes waste.", "Honesty is the best policy.", "Hope for the best, prepare for the worst.",
    "If it ain't broke, don't fix it.", "Ignorance is bliss.",
    "Laughter is the best medicine.", "Look before you leap.", "Love is blind.",
    "Necessity is the mother of invention.", "No news is good news.",
    "Old habits die hard.", "Once bitten, twice shy.", "Practice makes perfect.",
    "Rome wasn't built in a day.", "Silence is golden.",
    "Still waters run deep.", "The best things in life are free.", "The grass is always greener on the other side.",
    "The pen is mightier than the sword.", "There's no place like home.",
    "Time is money.", "Time heals all wounds.", "Variety is the spice of life.",
    "When in Rome, do as the Romans do.", "Where there's a will, there's a way.",
    "You can't judge a book by its cover.", "You can't make an omelet without breaking a few eggs.",
    "You can't teach an old dog new tricks.", "A stitch in time saves nine.",
    "Absence makes the heart grow fonder.", "All that glitters is not gold.",
    "An apple a day keeps the doctor away.", "A penny saved is a penny earned.",
    "A watched pot never boils.", "Beauty is only skin deep.",
    "Blood is thicker than water.", "Curiosity killed the cat.",
    "Don't count your chickens before they hatch.", "Don't put all your eggs in one basket.",
    "Every dog has its day.", "Familiarity breeds contempt.", "Great minds think alike.",
    "It's a small world.", "It's better to be safe than sorry.", "Knowledge is power.",
    "Misery loves company.", "Money doesn't grow on trees.",
    "Never look a gift horse in the mouth.", "No pain, no gain.",
    "Opposites attract.", "Patience is a virtue.", "Seeing is believing.",
    "Strike while the iron is hot.", "The apple doesn't fall far from the tree.",
    "The best defense is a good offense.", "The devil is in the details.",
    "The early bird gets the worm.", "The ends justify the means.",
    "The road to hell is paved with good intentions.", "There is no such thing as a free lunch.",
    "There's no such thing as bad publicity.", "To err is human; to forgive, divine.",
    "Two heads are better than one.", "Two wrongs don't make a right.",
    "What goes around comes around.", "When the cat's away, the mice will play.",
    "You can lead a horse to water, but you can't make him drink.",
    "You can't always get what you want.", "You reap what you sow.",
    "A bad workman always blames his tools.", "A rolling stone gathers no moss.",
    "All work and no play makes Jack a dull boy.", "Don't throw the baby out with the bathwater.",
    "Every rose has its thorn.", "Good fences make good neighbors.",
    "He who laughs last laughs longest.", "If the shoe fits, wear it.",
    "It's not over till the fat lady sings.", "Let sleeping dogs lie.",
    "Many hands make light work.", "Too many cooks spoil the broth.",
    "You catch more flies with honey than with vinegar.", "Absence sharpens love, presence strengthens it.",
    "A chain is only as strong as its weakest link.", "A friend in need is a friend indeed.",
    "A leopard can't change its spots.", "All's fair in love and war."
]
public let swearWords = ["Arsehole", "Asshat", "Asshole", "Big black cock", "Bitch (slang)", "Bloody", "Blowjob", "Bugger", "Bullshit", "Chicken shit", "Clusterfuck", "Cock (slang)", "Cocksucker", "Coonass", "Cornhole (slang)", "Cox–Zucker machine", "Cracker (term)", "Cunt", "Dafuq", "Damn", "Dick (slang)", "Enshittification", "Faggot", "Feck", "Fuck", "Fuck her right in the pussy", "marry", "kill", "Fuckery", "Grab","em by the pussy", "Healslut", "Motherfucker", "Nigga", "Nigger", "Use of nigger in proper names", "Paki (slur)", "Poof", "Poofter", "Prick (slang)", "Pussy", "Ratfucking", "Retard (pejorative)", "Shit", "Shit happens", "Shithouse", "Shitter", "Shut the fuck up", "Shut the hell up", "Slut", "Son of a bitch", "Spic", "Twat", "Wanker", "Whore"]
